/* tempinit.c - tempinit */

#define TSC_ADC_START 0x44e0D000
/* 
 * All of the TSC_ADC_SS registers:
 * */

#define REVISION (TSC_ADC_START+0x00)
#define SYSCONFIG (TSC_ADC_START+0x10)
#define IRQSTATUS_RAW (TSC_ADC_START+0x24)
#define IRQSTATUS (TSC_ADC_START+0x28)
#define IRQENABLE_SET (TSC_ADC_START+0x2c)
#define IRQENABLE_CLR (TSC_ADC_START+0x30)
#define IRQWAKEUP (TSC_ADC_START+0x34)
#define DMAENABLE_SET (TSC_ADC_START+0x38)
#define DMAENABLE_CLR (TSC_ADC_START+0x3C)
#define TSC_ADC_CTRL (TSC_ADC_START+0x40)
#define ADCSTAT (TSC_ADC_START+0x44)
#define ADCRANGE (TSC_ADC_START+0x48)
#define ADC_CLKDIV (TSC_ADC_START+0x4c)
#define ADC_MISC (TSC_ADC_START+0x50)
#define STEPENABLE (TSC_ADC_START+0x54)
#define IDLECONFIG (TSC_ADC_START+0x58)
#define TS_CHARGE_STEPCONFIG (TSC_ADC_START+0x5c)
#define TS_CHARGE_DELAY (TSC_ADC_START+0x60)
#define STEPCONFIG1 (TSC_ADC_START+0x64)
#define STEPDELAY1 (TSC_ADC_START+0x68)
#define STEPCONFIG2 (TSC_ADC_START+0x6c)
#define STEPDELAY2 (TSC_ADC_START+0x70)
#define STEPCONFIG3 (TSC_ADC_START+0x74)
#define STEPDELAY3 (TSC_ADC_START+0x78)
#define STEPCONFIG4 (TSC_ADC_START+0x7c)
#define STEPDELAY4 (TSC_ADC_START+0x80)
#define STEPCONFIG5 (TSC_ADC_START+0x84)
#define STEPDELAY5 (TSC_ADC_START+0x88)
#define STEPCONFIG6 (TSC_ADC_START+0x8c)
#define STEPDELAY6 (TSC_ADC_START+0x90)
#define STEPCONFIG7 (TSC_ADC_START+0x94)
#define STEPDELAY7 (TSC_ADC_START+0x98)
#define STEPCONFIG8 (TSC_ADC_START+0x9c)
#define STEPDELAY8 (TSC_ADC_START+0xA0)
#define STEPCONFIG9 (TSC_ADC_START+0xA4)
#define STEPDELAY9 (TSC_ADC_START+0xA8)
#define STEPCONFIG10 (TSC_ADC_START+0xAc)
#define STEPDELAY10 (TSC_ADC_START+0xB0)
#define STEPCONFIG11 (TSC_ADC_START+0xB4)
#define STEPDELAY11 (TSC_ADC_START+0xB8)
#define STEPCONFIG12 (TSC_ADC_START+0xBc)
#define STEPDELAY12 (TSC_ADC_START+0xC0)
#define STEPCONFIG13 (TSC_ADC_START+0xC4)
#define STEPDELAY13 (TSC_ADC_START+0xC8)
#define STEPCONFIG14 (TSC_ADC_START+0xCc)
#define STEPDELAY14 (TSC_ADC_START+0xD0)
#define STEPCONFIG15 (TSC_ADC_START+0xD4)
#define STEPDELAY15 (TSC_ADC_START+0xD8)
#define STEPCONFIG16 (TSC_ADC_START+0xDc)
#define STEPDELAY16 (TSC_ADC_START+0xE0)
#define FIFO0COUNT (TSC_ADC_START+0xE4)
#define FIFO0THRESHOLD (TSC_ADC_START+0xE8)
#define DMA0REQ (TSC_ADC_START+0xEC)
#define FIFO1COUNT (TSC_ADC_START+0xF0)
#define FIFO1THRESHOLD (TSC_ADC_START+0xF4)
#define DMA1REQ (TSC_ADC_START+0xF8)
#define FIFO0DATA (TSC_ADC_START+0x100)
#define FIFO1DATA (TSC_ADC_START+0x200)

#define CTRL_BASE 0x44E10000

//clock module wakup regitsers
#define CM_WAKEUP_ADDR 0x44e00400
//no idea
#define BBIO_CM_WKUP_OFFSET_FROM_CM_PER 0xBC
//check out DMA requests

#include <xinu.h>

devcall tempinit(
		 struct dentry *devptr
){
	kprintf("inittemp\n");
	//configure clock (adc won't work without this)
	*(uint32*)(CM_WAKEUP_ADDR+BBIO_CM_WKUP_OFFSET_FROM_CM_PER) = 0x2;
	kprintf("set clock\n");
	//enable writing to stepconfig registers
	*(uint32*)TSC_ADC_CTRL |= 0x04;
	*(uint32*)STEPENABLE = 0x06;
	*(uint32*)STEPCONFIG1 = 0x01;
	*(uint32*)STEPCONFIG2 = 0x01;
	//now enabling device
	*(uint32*)TSC_ADC_CTRL |= 0x01;
	kprintf("...inittemp done\n");
	return OK;
}
